# Generated by Django 3.2.6 on 2022-10-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Warga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('IN', 'Indonesia'), ('US', 'Unitid State')], max_length=10, verbose_name='Negara Asal')),
                ('name', models.CharField(max_length=255, verbose_name='Nama')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Fimale', 'Fimale')], max_length=10, verbose_name='Jenis Kelamin')),
                ('age', models.CharField(max_length=5, verbose_name='Alamat')),
                ('address', models.CharField(max_length=255, verbose_name='Alamat')),
            ],
            options={
                'verbose_name': 'Alamat',
            },
        ),
    ]
