# Generated by Django 3.2.6 on 2022-10-31 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penduduk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warga',
            options={'verbose_name': 'Warga Negara'},
        ),
    ]
