# Generated by Django 3.2.6 on 2022-10-31 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penduduk', '0002_alter_warga_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warga',
            name='age',
            field=models.IntegerField(verbose_name='Usia'),
        ),
    ]
